name: master

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: traq
  IMAGE_TAG: master

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set TRAQ_VERSION env
        run: echo "TRAQ_VERSION=master-SNAPSHOT" >> $GITHUB_ENV
      - name: Set TRAQ_REVISION env
        run: echo "TRAQ_REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Show available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: hijiki51
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            TRAQ_VERSION=${{ env.TRAQ_VERSION }}
            TRAQ_REVISION=${{ env.TRAQ_REVISION }}
          tags: |
            ghcr.io/hijiki51/${{ env.IMAGE_NAME }}:master
  scan:
    name: Scan Image Vulnerability
    runs-on: ubuntu-latest
    needs: [image]
    steps:
      - uses: actions/checkout@v3
      - name: Pull docker image
        run: docker pull ghcr.io/hijiki51/${IMAGE_NAME}:${IMAGE_TAG}
      - name: Container image scan
        uses: Azure/container-scan@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ghcr.io/hijiki51/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  deploy-staging:
    name: Deploy staging
    runs-on: ubuntu-latest
    needs: [image]
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.STAGING_SSH_KEY }}
          known_hosts: ${{ secrets.STAGING_KNOWN_HOSTS }}
      - name: Deploy
        run: ssh -o LogLevel=QUIET -t ${{ secrets.STAGING_DEPLOY_USER }}@${{ secrets.STAGING_DEPLOY_HOST }} "sudo sh /srv/traQ-dev-server/deploy.sh traq-backend"
