name: release

on:
  push:
    tags:
      - v*.*.*
    branches-ignore:
      - '**'

env:
  IMAGE_NAME: traq

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env
        run: echo "IMAGE_TAG=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set TRAQ_VERSION env
        run: echo "TRAQ_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Set TRAQ_REVISION env
        run: echo "TRAQ_REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Show available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: hijiki51
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            TRAQ_VERSION=${{ env.TRAQ_VERSION }}
            TRAQ_REVISION=${{ env.TRAQ_REVISION }}
          tags: |
            ghcr.io/hijiki51/${{ env.IMAGE_NAME }}:latest
            ghcr.io/hijiki51/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # goreleaserがchangelogを生成する用
          fetch-depth: 0
      - name: Read Go version
        run: echo "GO_VERSION=$(cat ./.go-version)" >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
